# Generated by Django 3.0.3 on 2020-02-13 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200213_1848'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostImages',
            new_name='PostImage',
        ),
    ]
