# Generated by Django 3.0.3 on 2020-02-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200213_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
