# Generated by Django 3.0.3 on 2020-02-10 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=180)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=250)),
                ('specialization', models.CharField(max_length=250)),
                ('date_started', models.DateField()),
                ('date_finished', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SourceCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=180)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=180)),
                ('city', models.CharField(blank=True, max_length=20)),
                ('url', models.URLField()),
                ('position', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('date_started', models.DateField()),
                ('date_finished', models.DateField()),
                ('personal_projects', models.ManyToManyField(blank=True, to='cv.PersonalProject')),
                ('source_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.SourceCode')),
                ('technologies', models.ManyToManyField(to='cv.Technology')),
            ],
        ),
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('contacts', models.ManyToManyField(to='cv.Contact')),
                ('education', models.ManyToManyField(to='cv.Education')),
                ('experience', models.ManyToManyField(to='cv.Experience')),
                ('languages', models.ManyToManyField(to='cv.Language')),
                ('technologies', models.ManyToManyField(to='cv.Technology')),
            ],
        ),
    ]
