# Generated by Django 3.0.8 on 2020-07-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('logo', models.ImageField(upload_to='icons')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('bio', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='photo')),
                ('cv', models.FileField(upload_to='cv')),
                ('social_media', models.ManyToManyField(blank=True, to='cv.SocialMedia')),
            ],
        ),
    ]
