# Generated by Django 3.0.3 on 2020-02-10 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_auto_20200210_1741'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cv',
            options={'verbose_name': 'CV', 'verbose_name_plural': 'Resumes'},
        ),
    ]
