# Generated by Django 3.0.3 on 2020-02-11 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_language_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='level',
            field=models.CharField(choices=[('Elementary', 'Elementary'), ('Intermediate', 'Intermediate'), ('Upper-intermediate', 'Upper-intermediate'), ('Advanced', 'Advanced'), ('Native', 'Native')], max_length=20),
        ),
    ]
