# Generated by Django 3.0.3 on 2020-02-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_auto_20200211_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='contacts',
        ),
        migrations.AddField(
            model_name='cv',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='cv',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
