# Generated by Django 3.0.3 on 2020-02-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0006_auto_20200211_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='image',
            field=models.ImageField(blank=True, upload_to='photo'),
        ),
    ]
