# Generated by Django 3.0.3 on 2020-02-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0007_cv_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('logo', models.ImageField(upload_to='icons')),
                ('url', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='cv',
            name='github',
        ),
        migrations.AddField(
            model_name='cv',
            name='social_media',
            field=models.ManyToManyField(blank=True, to='cv.SocialMedia'),
        ),
    ]
