# Generated by Django 3.0.3 on 2020-02-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0008_auto_20200213_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
