# Generated by Django 3.0.3 on 2020-07-07 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0009_cv_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cv',
            old_name='social_media',
            new_name='links',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('bio', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='photo')),
                ('social_media', models.ManyToManyField(blank=True, to='cv.SocialMedia')),
            ],
        ),
    ]
